#pragma once


typedef enum
{
    MESSAGE_TYPE_ERROR = 1,
    MESSAGE_TYPE_WARNING,
    MESSAGE_TYPE_INFO,
    MESSAGE_TYPE_LOG,
} message_type_t;

typedef enum
{
    FILE_CHANGE_TYPE_CREATED = 1,
    FILE_CHANGE_TYPE_CHANGED,
    FILE_CHANGE_TYPE_DELETED,
} file_change_type_t;

typedef enum
{
    WATCH_KIND_CREATE = 1,
    WATCH_KIND_CHANGE,
    WATCH_KIND_DELETE,
} watch_kind_t;

typedef enum
{
    TEXT_DOCUMENT_SYNC_KIND_NONE,
    TEXT_DOCUMENT_SYNC_KIND_FULL,
    TEXT_DOCUMENT_SYNC_KIND_INCREMENTAL,
} text_document_sync_kind_t;

typedef enum
{
    DIAGNOSTIC_SEVERITY_ERROR = 1,
    DIAGNOSTIC_SEVERITY_WARNING,
    DIAGNOSTIC_SEVERITY_INFORMATION,
    DIAGNOSTIC_SEVERITY_HINT,
} diagnostic_severity_t;

typedef enum
{
    COMPLETION_ITEM_KIND_TEXT = 1,
    COMPLETION_ITEM_KIND_METHOD = 2,
    COMPLETION_ITEM_KIND_FUNCTION = 3,
    COMPLETION_ITEM_KIND_CONSTRUCTOR = 4,
    COMPLETION_ITEM_KIND_FIELD = 5,
    COMPLETION_ITEM_KIND_VARIABLE = 6,
    COMPLETION_ITEM_KIND_CLASS = 7,
    COMPLETION_ITEM_KIND_INTERFACE = 8,
    COMPLETION_ITEM_KIND_MODULE = 9,
    COMPLETION_ITEM_KIND_PROPERTY = 10,
    COMPLETION_ITEM_KIND_UNIT = 11,
    COMPLETION_ITEM_KIND_VALUE = 12,
    COMPLETION_ITEM_KIND_ENUM = 13,
    COMPLETION_ITEM_KIND_KEYWORD = 14,
    COMPLETION_ITEM_KIND_SNIPPET = 15,
    COMPLETION_ITEM_KIND_COLOR = 16,
    COMPLETION_ITEM_KIND_FILE = 17,
    COMPLETION_ITEM_KIND_REFERENCE = 18,
} completion_item_kind_t;

typedef enum
{
    INSERT_TEXT_FORMAT_PLAIN_TEXT = 1,
    INSERT_TEXT_FORMAT_SNIPPET,
} insert_text_format_t;

typedef enum
{
    DOCUMENT_HIGHLIGHT_KIND_TEXT = 1,
    DOCUMENT_HIGHLIGHT_KIND_READ,
    DOCUMENT_HIGHLIGHT_KIND_WRITE,
} document_highlight_kind_t;

typedef enum
{
    SYMBOL_KIND_FILE = 1,
    SYMBOL_KIND_MODULE = 2,
    SYMBOL_KIND_NAMESPACE = 3,
    SYMBOL_KIND_PACKAGE = 4,
    SYMBOL_KIND_CLASS = 5,
    SYMBOL_KIND_METHOD = 6,
    SYMBOL_KIND_PROPERTY = 7,
    SYMBOL_KIND_FIELD = 8,
    SYMBOL_KIND_CONSTRUCTOR = 9,
    SYMBOL_KIND_ENUM = 10,
    SYMBOL_KIND_INTERFACE = 11,
    SYMBOL_KIND_FUNCTION = 12,
    SYMBOL_KIND_VARIABLE = 13,
    SYMBOL_KIND_CONSTANT = 14,
    SYMBOL_KIND_STRING = 15,
    SYMBOL_KIND_NUMBER = 16,
    SYMBOL_KIND_BOOLEAN = 17,
    SYMBOL_KIND_ARRAY = 18,
} symbol_kind_t;

typedef enum
{
    TEXT_DOCUMENT_SAVE_REASON_MANUAL = 1,
    TEXT_DOCUMENT_SAVE_REASON_AFTER_DELAY,
    TEXT_DOCUMENT_SAVE_REASON_FOCUS_OUT,
} text_document_save_reason_t;
